#pragma once

enum class AssetID {
    PLAYER_WOLF,
    ENEMY_ASHIGARU,
    ENEMY_MINIBOSS,
    ENEMY_FINALBOSS,
    SFX_COIN,
    SFX_HIT,
    SFX_DASH,
    SFX_DEFLECT_1,
    SFX_DEFLECT_2,
    SFX_DEFLECT_NPC,
    SFX_BLOCK,
    SFX_DEATHBLOW,
    SFX_WALK,
    SFX_RUN,
    SFX_LAND,
    SFX_SLASH,
    SFX_HEAL,
    SFX_SMOKE,
    SFX_BREAK,
    BGM_COMBAT,
    BGM_EXPLORE,
    BGM_MENU,
    BGM_VICTORY,
    BGM_RETURN
};
