#pragma once

enum class AssetID {
    PLAYER_WOLF,
    ENEMY_ASHIGARU,
    ENEMY_MINIBOSS,
    ENEMY_FINALBOSS,
    ENEMY_KIMONO,
    SFX_COIN,
    SFX_HIT,
    SFX_DASH,
    SFX_DEFLECT_1,
    SFX_DEFLECT_2,
    SFX_DEFLECT_NPC,
    SFX_BLOCK,
    SFX_DEATHBLOW
};
