"""Turn the campfire .fbx into the two .glb files the game draws.

    assets/props/campfire_body.glb    stones, dirt and logs -- always drawn
    assets/props/campfire_flame.glb   the four flame shells -- drawn when lit

Two files rather than a lit and an unlit variant, because the flame does not
just need to be *toggled*, it needs to be drawn **differently**: additively
blended and unlit, in its own pass, after the opaque geometry. A combined model
could not express that, and two full variants would ship the stones twice.
So "unlit campfire" is the body alone and "lit" is the body plus one more draw.

WHY ADDITIVE, AND WHY IT IS NOT OPTIONAL

The asset's flame is four nested shells -- red outside, then orange, then
yellow, with a white core -- and that is where the colour gradient in the
artist's preview comes from. Measured here, every one of them is a single
closed watertight mesh (one connected component, zero boundary edges), and each
is strictly smaller than the one around it:

    fire_red      972 tris   86.0 mm wide   93.0 mm tall
    orange_fire   768 tris   66.4 mm        87.5 mm
    yellow_fire   588 tris   44.8 mm        76.0 mm
    whitefire     300 tris   34.3 mm        53.2 mm

Drawn opaque, the red shell hides the other three completely: you get a solid
red cone plus 1,656 triangles that never produce a visible pixel. The preview
shows the gradient because it composited the shells with transparency.

Additive blending gets it back, and better than alpha would: the shells *sum*,
so the middle -- where all four overlap -- goes white hot and the edge, where
only red covers, stays red. It is also order-independent, which matters because
these are concentric and any depth sort would be arbitrary.

WHAT THIS FIXES ON THE WAY

Every texture in the .fbx points at the original author's machine, as a Windows
absolute path glued onto whatever directory the file is read from:

    .../low-poly-campfire/source/C:/Users/erics/OneDrive/Pictures/textures/redmountain.png

Blender loads those at 0x0 without complaining and the model exports
untextured. They are repointed at the textures/ directory that ships beside the
.fbx and packed into the .blend so the exporter embeds them. `logwood` also
asks for a .tx -- a RenderMan texture -- where a .png is what shipped, so the
extension is remapped too.

And the model is authored at 17 cm across, because its root carries a 0.01
scale. It is normalised here to TARGET_WIDTH with its base on the origin, so
the game can place it at a ground point with no magic numbers at the call site.

Usage:
    blender --background --python tools/make_campfire.py -- [--out-dir assets/props]
        [--width 1.2] [--dry-run]
"""

import argparse
import math
import os
import sys

import bpy
from mathutils import Matrix, Vector

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_FBX = os.path.join(ROOT, "assets", "low-poly-campfire", "source",
                          "campfire.fbx")
TEXTURE_DIR = os.path.join(ROOT, "assets", "low-poly-campfire", "textures")

# Which texture each material actually wants, by material name. The .fbx's own
# paths are unusable (see the module docstring), so this is the mapping, stated
# once, rather than a guess made per material at import time.
TEXTURES = {
    "dirt": "redmountain.png",
    "rock": "redmountain.png",
    "logg": "hardwood.png",
    "logwood": "lightwood.png",   # the .fbx asks for lightwood.tx
}

# The flame, identified by material rather than by object name. Object names in
# this file are Maya's autogenerated polySurfaceNN, which carry no meaning and
# would silently reshuffle if the asset were ever re-exported; the material
# names are what the artist actually chose.
FLAME_MATERIALS = ("fire_red", "orange_fire", "yellow_fire", "whitefire")

# Plan width in metres, against a 1.8 m player. The source is 0.174 m across --
# a coaster -- because its root empty carries a 0.01 scale.
#
# 2.4 makes it a fire pit a little wider than the player is tall, which is the
# size a thing has to be before it reads as a landmark you walk *to* rather than
# scenery you walk past. That matters here: this is the phase's exit.
TARGET_WIDTH = 2.4

BODY_NAME = "campfire_body.glb"
FLAME_NAME = "campfire_flame.glb"


class BuildError(Exception):
    """Something about the source asset is not what this expects."""


def patch_fbx_light_import():
    """Let import_scene.fbx run on Blender 5.2.

    The importer sets `lamp.cycles.cast_shadow`, which this Cycles no longer
    has, and the AttributeError aborts the whole operator -- meshes included --
    over a light this asset does not need. The one line is compiled out rather
    than the exception swallowed, so a *different* failure still surfaces.
    """
    import inspect
    import textwrap

    from io_scene_fbx import import_fbx

    source = inspect.getsource(import_fbx.blen_read_light)
    marker = "lamp.cycles.cast_shadow = lamp.use_shadow"
    if marker not in source:
        return  # Fixed upstream.
    exec(compile(textwrap.dedent(source).replace(marker, "pass"),
                 "<make_campfire: patched>", "exec"), import_fbx.__dict__)


def repoint_textures():
    """Give every textured material an image that actually resolves.

    Loud rather than best-effort: a material left pointing at the author's
    C:\\Users path exports as untextured white, and that failure looks like a
    modelling problem rather than a path problem. Anything unmapped is named.
    """
    fixed, missing = [], []
    for material in bpy.data.materials:
        wanted = TEXTURES.get(material.name)
        if wanted is None:
            continue  # A flame material; it carries a flat colour, not an image.

        path = os.path.join(TEXTURE_DIR, wanted)
        if not os.path.exists(path):
            missing.append("%s wants %s" % (material.name, path))
            continue

        image = bpy.data.images.load(path, check_existing=True)
        image.pack()
        for node in material.node_tree.nodes:
            if node.type == "TEX_IMAGE":
                node.image = image
        fixed.append("%s -> %s" % (material.name, wanted))

    if missing:
        raise BuildError("textures not found:\n  " + "\n  ".join(missing))
    return fixed


def is_flame(obj):
    names = {m.name for m in obj.data.materials if m}
    hit = names & set(FLAME_MATERIALS)
    if hit and names - hit:
        # A mesh that mixes flame and body materials could not be put in either
        # file without dragging the other's geometry along.
        raise BuildError(
            "%s carries both flame (%s) and body (%s) materials, so it cannot "
            "be split. The asset's flame used to be four meshes of its own."
            % (obj.name, ", ".join(sorted(hit)), ", ".join(sorted(names - hit))))
    return bool(hit)


def flatten_and_normalise(objects, target_width):
    """Bake every transform into the mesh data, scale, and sit the base on 0.

    Done by transforming the meshes directly rather than through
    bpy.ops.object.parent_clear + transform_apply. Those are context-sensitive
    operators, and in --background the parent clear dropped the root empty's
    0.01 scale instead of baking it -- the campfire came out a hundred times
    too big, silently. Matrix maths has no context to get wrong.

    The .fbx hangs everything off one empty carrying that 0.01 and the Maya
    Z-up rotation, so folding it in here is also what lets the two exports
    share one frame and lets the game forget the empty existed.

    Origin ends up at the centre of the footprint and at the *bottom* of the
    model, so placing a campfire is "put it at the ground point" -- no offset to
    remember, nothing to get wrong per call site.
    """
    corners = []
    for obj in objects:
        corners.extend(obj.matrix_world @ Vector(c) for c in obj.bound_box)
    lo = Vector((min(c.x for c in corners), min(c.y for c in corners),
                 min(c.z for c in corners)))
    hi = Vector((max(c.x for c in corners), max(c.y for c in corners),
                 max(c.z for c in corners)))

    width = max(hi.x - lo.x, hi.y - lo.y)
    if width <= 0.0:
        raise BuildError("the campfire has no plan extent to scale from.")
    scale = target_width / width
    base = Vector(((lo.x + hi.x) * 0.5, (lo.y + hi.y) * 0.5, lo.z))

    normalise = Matrix.Scale(scale, 4) @ Matrix.Translation(-base)

    # Guarded against shared mesh data: two objects on one mesh would otherwise
    # transform it twice and put the second one somewhere absurd.
    done = set()
    for obj in objects:
        if obj.data.name in done:
            raise BuildError(
                "%s shares mesh data with another object. Baking the transform "
                "would apply twice." % obj.name)
        done.add(obj.data.name)
        obj.data.transform(normalise @ obj.matrix_world)
        obj.parent = None
        obj.matrix_world = Matrix.Identity(4)

    return {"was_width_mm": width * 1000.0, "scale": scale,
            "height": (hi.z - lo.z) * scale}


def export(objects, path):
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.select_set(True)
    # Draco and KTX2 are off for the reason tools/export_level.py states: raylib
    # is on cgltf, supports neither, and a model using either arrives with no
    # geometry rather than with an error.
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=True,
        export_draco_mesh_compression_enable=False,
        export_image_format="AUTO",
        export_cameras=False,
        export_lights=False,
        export_animations=False,
        export_skins=False,
    )


def parse_args(argv):
    argv = argv[argv.index("--") + 1:] if "--" in argv else []
    parser = argparse.ArgumentParser(prog="make_campfire.py")
    parser.add_argument("--out-dir",
                        default=os.path.join(ROOT, "assets", "props"))
    parser.add_argument("--width", type=float, default=TARGET_WIDTH,
                        help="plan width in metres (default %.2f)"
                             % TARGET_WIDTH)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args(argv)


def main():
    args = parse_args(sys.argv)

    if not os.path.exists(SOURCE_FBX):
        raise BuildError("campfire source not found at %s" % SOURCE_FBX)

    patch_fbx_light_import()
    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.import_scene.fbx(filepath=SOURCE_FBX)

    fixed = repoint_textures()

    meshes = [o for o in bpy.data.objects if o.type == "MESH"]
    if not meshes:
        raise BuildError("%s imported no meshes." % SOURCE_FBX)
    for obj in list(bpy.data.objects):
        if obj.type != "MESH":
            bpy.data.objects.remove(obj, do_unlink=True)

    flame = [o for o in meshes if is_flame(o)]
    body = [o for o in meshes if not is_flame(o)]
    if not flame:
        raise BuildError("no mesh carries any of %s; the flame cannot be split "
                         "out." % ", ".join(FLAME_MATERIALS))
    if not body:
        raise BuildError("every mesh is flame; there is no campfire to draw "
                         "when it is unlit.")

    shape = flatten_and_normalise(meshes, args.width)

    def tris(objs):
        return sum(len(p.vertices) - 2 for o in objs for p in o.data.polygons)

    print("\n[make_campfire] textures  %s" % ", ".join(fixed))
    print("[make_campfire] scale     %.1f mm wide -> %.2f m (x%.2f), %.2f m tall"
          % (shape["was_width_mm"], args.width, shape["scale"],
             shape["height"]))
    print("[make_campfire] body      %d meshes, %d tris" % (len(body), tris(body)))
    print("[make_campfire] flame     %d meshes, %d tris -- drawn additively, so "
          "all four shells contribute" % (len(flame), tris(flame)))
    for obj in sorted(flame, key=lambda o: o.name):
        names = ", ".join(sorted(m.name for m in obj.data.materials if m))
        print("[make_campfire]           %-14s %s" % (obj.name, names))

    if args.dry_run:
        print("[make_campfire] dry run -- nothing written")
        return

    os.makedirs(args.out_dir, exist_ok=True)
    export(body, os.path.join(args.out_dir, BODY_NAME))
    export(flame, os.path.join(args.out_dir, FLAME_NAME))
    print("[make_campfire] wrote     %s, %s"
          % (os.path.join(args.out_dir, BODY_NAME),
             os.path.join(args.out_dir, FLAME_NAME)))


if __name__ == "__main__":
    try:
        main()
    except BuildError as error:
        raise SystemExit("[make_campfire] %s" % error)
